// Matchup Model V2 research — fit the FROZEN prospective-shadow coefficients of Challenger B (mm2-B-context/1):
// the frozen configuration (lambda from the development window) on EVERY frozen dataset row per tour. Writes
// workers/shared/research/mm2-b-shadow.js (a constant; research-only shadow lane, never an API output).
//   node --max-old-space-size=14000 scripts/research/mm2/fit-shadow.mjs
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { DATA } from './lib/inputs.mjs';
import { fitLogistic } from './lib/model.mjs';
import { FEATURES_B, FEATURE_VERSION } from '../../../workers/shared/research/mm2-profile.js';

const frozen = JSON.parse(fs.readFileSync(path.join(DATA, 'frozen-config.json'), 'utf8'));
const ds = JSON.parse(fs.readFileSync(path.join(DATA, 'dataset/manifest.json'), 'utf8'));
if (ds.dataset_hash !== frozen.dataset_hash) throw new Error('dataset changed since the configuration was frozen');
const model = { model_version: 'mm2-B-context/1', feature_version: FEATURE_VERSION, dataset_hash: ds.dataset_hash, config_hash: frozen.config_hash, names: FEATURES_B, tours: {} };
for (const tour of ['ATP', 'WTA']) {
  const rows = fs.readFileSync(path.join(DATA, 'dataset', `${tour}.jsonl`), 'utf8').trim().split('\n').map((l) => JSON.parse(l));
  const m = fitLogistic(rows.map((r) => FEATURES_B.map((k) => r.features[k])), rows.map((r) => r.y), FEATURES_B, { lambda: frozen.tours[tour].lambda_B });
  model.tours[tour] = { lambda: frozen.tours[tour].lambda_B, rows: rows.length, fitted_through: rows.at(-1).scheduled_day, coef: m.coef.map((x) => Math.round(x * 1e8) / 1e8) };
  console.log(tour, JSON.stringify(model.tours[tour]));
}
model.coef_hash = crypto.createHash('sha256').update(JSON.stringify(model.tours)).digest('hex');
fs.writeFileSync('workers/shared/research/mm2-b-shadow.js', `// GENERATED by scripts/research/mm2/fit-shadow.mjs — FROZEN prospective-shadow coefficients of Challenger B.
// RESEARCH ONLY (docs/MATCHUP_MODEL_V2_RESEARCH.md): used by the shadow writer, never by an API response.
export const SHADOW_MODEL = Object.freeze(${JSON.stringify(model, null, 1)});
`);
console.log('coef_hash', model.coef_hash);
